[package]
name = "exp1"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
hex-literal = "0.4.1"
num-bigint = {version = "0.4.4", features = ["rand"]}
rand = "0.8.5"
sha2 = "0.10.8"
